jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout epoxy
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setting up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: liberica
        java-version: '11'
    - continue-on-error: true
      name: Build / Unit tests / Lint
      run: ./gradlew check --stacktrace
    - continue-on-error: true
      name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
        arch: x86_64
        emulator-build: 7425822
        emulator-options: -no-skin -no-window
        script: ./gradlew :epoxy-composeinterop-maverickssample:connectedDebugAndroidTest
          --stacktrace
        target: default
name: Build/Test
on:
  repository_dispatch:
    types: trigger-ga___build_test.yml
